# Generated by Django 2.0.6 on 2018-06-21 04:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postvote',
            options={'verbose_name': 'Оценка заметки', 'verbose_name_plural': 'Оценки заметок'},
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together={('author', 'post')},
        ),
    ]
